cc_inc_library (
    name = "profile",
    hdrs = ["profile.h"],
    visibility = ["//visibility:public"],
    deps = [
        "profile_impl"
    ]
)

cc_library (
   name = "profile_impl",
   srcs = ["profile.cc"],
   hdrs = ["profile.h"],
   visibility = ["//visibility:public"]
)